import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import {useState} from "react";




import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";





export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>hectorfr-portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

        </Head>

        <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
          <section className=" h-screen ">
            <nav className= "py-10 mb-12 flex justify-between">
              <h1 className="text-xl font-burtons">Helloworld</h1> 
              <ul className= "flex items-center">
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/>
                </li>
                  <li><a className="bg-gradient-to-r from-cyan-500 to-cyan-800 text-white px-4 py-2 rounded-md ml-8" href="#">
                  Resume
                  </a></li>
              </ul>
            </nav>
            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
                Hectorfr
              </h2>
              <h3 className="text-2xl py-2 md:text-3xl">
                Software developer
              </h3>
              <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
                Freelancer providing services for any programming needs, cursing Computer Science in University.
                Join me in my adventures, and dont hesitate to contact me for any purpose.
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />

            </div>
  
          </section>

          
          <section> 
            <div>

              <h3 className="text-3xl py-2 mt-10">Services I offer</h3>
              <p className="text-md py-5 leading-8 text-gray-80">
                I offer many things like this and the other.
                <span className="text-teal-500">But also this</span>But also the other
              </p>
            </div>

            <div className="lg:flex gap-10">
                <div className="text-center shadow-lg p-10 rounded-xl my-10">
                  <Image src={design} width={100} height={100}/>

                  <h3 className="text-lg font-medium pt-8 pb-2">Beautifull designs</h3>
                  <p className="py-2">
                    Creating nice and elegant designs 
                  </p>

                  <h4 className="py-2 text-teal-600">Design tools I use</h4>

                </div>

                <div className="text-center shadow-lg p-10 rounded-xl my-10">
                  <Image src={code} width={100} height={100}/>

                  <h3 className="text-lg font-medium pt-8 pb-2">Beautifull designs</h3>
                  <p className="py-2">
                    Creating nice and elegant designs 
                  </p>

                  <h4 className="py-2 text-teal-600">Design tools I use</h4>

                </div>

                <div className="text-center shadow-lg p-10 rounded-xl my-10">
                  <Image src={consulting} width={100} height={100}/>

                  <h3 className="text-lg font-medium pt-8 pb-2">Beautifull designs</h3>
                  <p className="py-2">
                    Creating nice and elegant designs 
                  </p>

                  <h4 className="py-2 text-teal-600">Design tools I use</h4>

                </div>
            </div>


          </section>



          <section>
            <div>

              <h3 className="text-3xl py-1">Projects</h3>

              <p className="text-md py-5 leading-8 text-gray-80">
                  I offer many things like this and the other.
                  <span className="text-teal-500">But also this</span>But also the other
              </p>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1"><Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
              <div className="basis-1/3 flex-1"><Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
              <div className="basis-1/3 flex-1"><Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
              <div className="basis-1/3 flex-1"><Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
              <div className="basis-1/3 flex-1"><Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
              <div className="basis-1/3 flex-1"><Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
            </div>
          </section>
        </main>


      </div>
  )
}
