import Head from "next/head";
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import {FaTerminal, FaUserSecret, FaJava} from 'react-icons/fa';
import {SiJavascript, SiTailwindcss, SiReact, SiPython, SiCplusplus} from 'react-icons/si';
import {TbBrandNextjs, TbScript} from 'react-icons/tb';
import {VscTerminalBash, VscTerminalPowershell, VscServerEnvironment} from 'react-icons/vsc';
import {BiShow, BiCar} from 'react-icons/bi';


import { GiTrophy } from 'react-icons/gi';
import {BsPersonVcardFill} from 'react-icons/bs'


import {useState} from "react";




import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";





export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>hectorfr-portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/circle.ico" />

        </Head>

        <main className="bg-emerald-200 px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white">
          <section className="h-screen">
            <nav className= "py-10 mb-8 flex justify-between">
              <h1 className="text-xl">
                <FaTerminal />
              </h1> 
              <ul className= "flex items-center">
                  <li>
                    <FaUserSecret onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl "/>
                  </li>
                  <li>
                    <a className="bg-gradient-to-r from-cyan-700 to-emerald-500 px-4 py-2 rounded-md ml-4" href="#projects">
                      Projects
                    </a>
                  </li>
              </ul>
            </nav>
            <div className="text-center">
              <h2 className="text-5xl text-sky-800 font-burtons md:text-6xl">
                hector fr
              </h2>
              <h3 className="text-2xl py-2 md:text-3xl">
                Software developer
              </h3>
            <div className="relative mx-auto bg-gradient-to-b from-sky-600 rounded-full w-80 h-80 mt-5 overflow-hidden border-8 border-sky-800 md:h-96 md:w-96">
                <Image src={deved} layout="fill" objectFit="cover" />
            </div>
  
              <p className="text-md py-5 leading-8 max-w-lg mx-auto p-10 md:text-xl">
                Freelancer providing services for any programming needs, currently studying <span className="text-blue-700">Computer Science</span> in University.
                I am keen to contiue building on with   <span className="text-blue-700">new challenges</span>, if you find this work interesting, you are more than welcome to contact me.
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-white">
                  <a href="https://www.linkedin.com/in/hector-fr/" target="_blank" rel="noreferrer" ><AiFillLinkedin /></a>
                  <a href="https://github.com/Hectorfr" target="_blank" rel="noreferrer"><AiFillGithub /></a>
            </div>
            
          </section>

          
          <section> 
            <div id="projects">
              <h3 className="text-3xl text-center py-2">Proyects Overview</h3>    
              <p className="py-2 p-10 text-center text-blue-700">
                For more info try cliking the icons!
              </p>
            </div>

            <div className="2xl:flex gap-10">
                <div className="mx-center text-center shadow-xl p-10 rounded-xl my-10 dark:shadow-2xl dark:border-1 dark:border-cyan-800">
                  <div className="flex items-center justify-center">
                    <a href="https://github.com/Hectorfr/myportfolio" target="_blank" rel="noreferrer" className="text-cyan-900">  
                      <BsPersonVcardFill size={80}/>
                    </a>
                  </div>
                  <h3 className="text-lg pt-8 pb-2 font-burtons font-bold">portfolio website</h3>
                  <p className="py-2 p-10">
                    In this project I have put to the test my front-end skills, where I have a created a website from scracth,
                    this a portfolio showcases my proyects and as such it has to recieve updates whenever I engage or finish one.
                    Also doing small changes to correct bugs and smooth out the user experience.
                  </p>

                  <h4 className="py-2 text-teal-600 dark:text-blue-700">Tools used</h4>
                  <div className="text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-white">
                    <SiTailwindcss />
                    <SiJavascript />
                    <SiReact />
                    <TbBrandNextjs />
                  </div>
                </div>


                <div className="mx-center text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-2xl dark:border-1 dark:border-cyan-800">
                  <div className="flex items-center justify-center">
                    <a href="https://github.com/Hectorfr/myportfolio" target="_blank" rel="noreferrer" className="text-cyan-900">  
                        <BiCar size={80}/>
                    </a>   
                 </div>
                  <h3 className="text-lg pt-8 pb-2 font-burtons font-bold">car detection</h3>
                  <p className="py-2 p-10">
                    Due to the importance of sleeping as much as possible during University, in this case I showcased my python skills
                    from a video the app captures the amount of cars crossing the main street conecting my house and University, to then makes
                    graphs to determine the best and worst times to leave for school in the morning.
                    I also learned about venv (virtual enviroments), with independent installation of python at any version and it's necessary dependencies for that specific project.

                  </p>

                  <h4 className="py-2 text-teal-600 dark:text-blue-700">Tools used</h4>
                  <div className="text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-white">
                    <SiPython />
                  </div>
                </div>


                <div className="mx-center text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-2xl dark:border-1 dark:border-cyan-800">
                <div className="flex items-center justify-center">
                    <a href="https://github.com/Hectorfr/myportfolio" target="_blank" rel="noreferrer" className="text-cyan-900">  
                        <TbScript size={80}/>
                    </a>   
                 </div>
                  <h3 className="text-lg pt-8 pb-2 font-burtons font-bold ">Scripting projects</h3>
                  <p className="py-2 p-10">
                    I fisrt learned about scripts in my first intern job, where they used complex and detailed scripts to automate operations, 
                    as this was a company with more than 400 operational servers, so I decided to learn about to it, understand it and do some scripting of my own.
                  </p>

                  <h4 className="py-2 text-teal-600 dark:text-blue-700">Tools used</h4>
                  <div className="text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-white">
                    <VscTerminalBash />
                    <VscTerminalPowershell />
                    <VscServerEnvironment />
                  </div>


                </div>

                <div className="mx-center text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-2xl dark:border-1 dark:border-cyan-800">
                <div className="flex items-center justify-center">
                    <a href="https://github.com/Hectorfr/myportfolio" target="_blank" rel="noreferrer" className="text-cyan-900">  
                        <GiTrophy size={80}/>
                    </a>   
                 </div>
                  <h3 className="text-lg pt-8 pb-2 font-burtons font-bold">Competitive programming</h3>
                  <p className="py-2 p-10">
                    CP is a concept which was introduced to me trough a friend in my first year in University, since then I have always been keen to learn more
                    and more algorithms, data structures, dynamic programming to get better at it, compete and keep on learning. Here is some of my work in this area.
                  </p>

                  <h4 className="py-2 text-teal-600 dark:text-blue-700">Tools used</h4>
                  <div className="text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-white">
                    <SiCplusplus />
                    <FaJava />
                  </div>
                </div>

            </div>
          </section>

          <section>
            .
          </section>

        
        </main>

        <footer className="bg-emerald-200 border-t-4 border-cyan-900 dark:bg-gray-900 ">
          <div className="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
            <span className="text-sm sm:text-center dark:text-gray-400">© 2023 <a className="hover:underline">Hector</a>. All Rights Reserved.
            </span>
          <ul className="flex flex-wrap items-center mt-3 text-sm font-medium dark:text-gray-400 sm:mt-0">
              <li>
                  <a href="#" className="mr-4 hover:underline md:mr-6 ">About me</a>
              </li>
              <li>
                  <a href="https://www.linkedin.com/in/hector-fr/" target="_blank" rel="noreferrer" className="hover:underline">Contact me through socials</a>
              </li>
          </ul>
          </div>
        </footer>


      </div>
  )
}
